### ISSUE TITLE
Remove build/ dir and add it to .gitignore

### ISSUE THREAD

**Issue by DanielSank** [episanty/TheYoungManTheStation#2]
It's usually discouraged to put binary files in a git repo. It's easy enough to clone the repo and build it. As it stands, the README is outsourced to the pdf in the build dir. This is nice because it shows the reader what the template actually looks like, but it's unorthodox and causes the user's very first impression (the README) to be unhelpful.

**Comment by episanty** [comment]
Fixed by https://github.com/episanty/TheYoungManTheStation/commit/4de95cb98d76131e3d290f7577fcd35f069d7e57 and https://github.com/episanty/TheYoungManTheStation/commit/eb658b60ba6cec1a15fb2d3a64031369d337d3f1.

**Comment by episanty** [comment]
(Unless you think that having some 300kB's worth of pdf and png is really fatal from a formalist git perspective, that is ;-).)
